from __future__ import annotations


def infer_source_stage(name: str) -> str:
    """Infer the producing stage for a session artifact."""
    if name in {"scan_plan", "device_readiness", "localization_readiness", "calibration_bundle", "localization_freeze", "manual_adjustment"}:
        return "workflow_lock"
    if name in {"summary_json", "summary_text", "quality_feedback", "camera_index", "ultrasound_index", "pressure_samples", "command_journal", "annotations"}:
        return "capture"
    if name in {"quality_timeline", "pressure_sensor_timeline", "ultrasound_frame_metrics", "alarm_timeline"}:
        return "preprocess"
    if name in {
        "frame_sync_index",
        "replay_index",
        "source_frame_set",
        "localization_replay_index",
        "reconstruction_input_index",
        "training_bridge_model_ready_input_index",
        "coronal_vpi",
        "bone_mask",
        "frame_anatomy_points",
        "lamina_candidates",
        "pose_series",
        "reconstruction_evidence",
        "spine_curve",
        "prior_assisted_curve",
        "landmark_track",
        "reconstruction_summary",
        "vpi_ranked_slices",
        "vpi_bone_feature_mask",
    }:
        return "reconstruction"
    if name in {
        "vertebra_pairs",
        "tilt_candidates",
        "cobb_measurement",
        "prior_assisted_cobb",
        "uca_measurement",
        "assessment_agreement",
        "assessment_summary",
        "assessment_overlay",
        "session_report",
        "session_compare",
        "session_trends",
        "diagnostics_pack",
        "qa_pack",
        "session_integrity",
        "ultrasound_analysis",
        "pressure_analysis",
        "lineage",
        "resume_state",
        "resume_decision",
        "resume_attempts",
        "resume_attempt_outcomes",
        "recovery_report",
        "operator_incident_report",
        "session_incidents",
        "event_log_index",
        "recovery_decision_timeline",
        "contract_consistency",
        "release_evidence_pack",
        "release_gate_decision",
        "command_state_policy",
        "event_delivery_summary",
        "selected_execution_rationale",
        "control_plane_snapshot",
        "control_authority_snapshot",
        "bridge_observability_report",
        "artifact_registry_snapshot",
        "session_evidence_seal",
    }:
        return "assessment"
    if name in {"registration_candidate", "back_roi", "midline_polyline", "landmarks", "body_surface", "guidance_targets"}:
        return "registration_build"
    return "session_service"


_DEPENDENCY_MAP: dict[str, list[str]] = {
    "device_readiness": ["scan_plan"],
    "localization_readiness": ["patient_registration", "calibration_bundle", "source_frame_set", "registration_candidate"],
    "calibration_bundle": ["scan_plan"],
    "localization_freeze": ["patient_registration", "localization_readiness", "calibration_bundle", "manual_adjustment", "source_frame_set"],
    "manual_adjustment": ["patient_registration"],
    "source_frame_set": ["scan_plan"],
    "registration_candidate": ["source_frame_set", "calibration_bundle"],
    "back_roi": ["source_frame_set"],
    "midline_polyline": ["back_roi"],
    "landmarks": ["midline_polyline"],
    "body_surface": ["midline_polyline"],
    "guidance_targets": ["registration_candidate"],
    "localization_replay_index": ["source_frame_set", "registration_candidate", "localization_readiness", "calibration_bundle"],
    "quality_timeline": ["quality_feedback"],
    "pressure_sensor_timeline": ["pressure_samples"],
    "ultrasound_frame_metrics": ["ultrasound_index", "pressure_samples", "quality_feedback"],
    "ultrasound_analysis": ["ultrasound_frame_metrics"],
    "pressure_analysis": ["pressure_sensor_timeline"],
    "alarm_timeline": ["command_journal"],
    "frame_sync_index": ["quality_feedback", "camera_index", "ultrasound_index", "pressure_samples", "annotations"],
    "replay_index": ["alarm_timeline", "quality_timeline", "pressure_sensor_timeline", "ultrasound_frame_metrics", "annotations", "frame_sync_index"],
    "reconstruction_input_index": ["patient_registration", "frame_sync_index", "quality_timeline", "pressure_sensor_timeline", "ultrasound_frame_metrics"],
    "coronal_vpi": ["reconstruction_input_index"],
    "training_bridge_model_ready_input_index": ["reconstruction_input_index"],
    "bone_mask": ["coronal_vpi"],
    "frame_anatomy_points": ["reconstruction_input_index"],
    "lamina_candidates": ["coronal_vpi", "bone_mask", "frame_anatomy_points", "reconstruction_input_index"],
    "pose_series": ["reconstruction_input_index"],
    "reconstruction_evidence": ["coronal_vpi", "bone_mask", "lamina_candidates"],
    "spine_curve": ["lamina_candidates", "patient_registration", "reconstruction_input_index"],
    "prior_assisted_curve": ["patient_registration", "reconstruction_input_index"],
    "landmark_track": ["spine_curve", "lamina_candidates", "patient_registration"],
    "reconstruction_summary": ["spine_curve", "landmark_track", "reconstruction_input_index", "reconstruction_evidence"],
    "vpi_ranked_slices": ["coronal_vpi"],
    "vpi_bone_feature_mask": ["vpi_ranked_slices", "coronal_vpi"],
    "vertebra_pairs": ["lamina_candidates"],
    "tilt_candidates": ["vertebra_pairs"],
    "cobb_measurement": ["vertebra_pairs", "tilt_candidates", "spine_curve", "landmark_track", "reconstruction_summary", "patient_registration"],
    "prior_assisted_cobb": ["cobb_measurement", "reconstruction_summary", "spine_curve"],
    "uca_measurement": ["vpi_ranked_slices", "vpi_bone_feature_mask", "coronal_vpi"],
    "assessment_agreement": ["cobb_measurement", "uca_measurement"],
    "assessment_summary": ["cobb_measurement", "uca_measurement", "assessment_agreement", "reconstruction_summary"],
    "assessment_overlay": ["cobb_measurement", "coronal_vpi"],
    "session_report": [
        "summary_json", "replay_index", "quality_timeline", "pressure_sensor_timeline", "ultrasound_frame_metrics",
        "ultrasound_analysis", "pressure_analysis", "alarm_timeline", "frame_sync_index", "reconstruction_summary",
        "assessment_summary", "cobb_measurement", "uca_measurement", "assessment_agreement",
    ],
    "session_compare": ["session_report", "assessment_summary"],
    "session_trends": ["session_report", "diagnostics_pack", "assessment_summary"],
    "diagnostics_pack": ["command_journal", "alarm_timeline", "quality_timeline", "pressure_sensor_timeline", "ultrasound_analysis", "pressure_analysis", "annotations", "assessment_summary"],
    "qa_pack": [
        "session_report", "replay_index", "quality_timeline", "pressure_sensor_timeline", "ultrasound_frame_metrics",
        "ultrasound_analysis", "pressure_analysis", "alarm_timeline", "session_compare", "session_trends", "diagnostics_pack",
        "reconstruction_summary", "spine_curve", "prior_assisted_curve", "landmark_track", "frame_anatomy_points", "lamina_candidates", "cobb_measurement", "prior_assisted_cobb", "uca_measurement",
        "assessment_summary", "assessment_agreement", "assessment_overlay", "vpi_ranked_slices", "vpi_bone_feature_mask",
    ],
    "session_integrity": ["scan_plan", "device_readiness", "xmate_profile", "patient_registration", "scan_protocol"],
    "lineage": ["scan_plan", "patient_registration", "command_journal", "session_report"],
    "resume_state": ["scan_plan", "command_journal", "session_integrity", "recovery_report"],
    "recovery_report": ["command_journal", "alarm_timeline", "annotations"],
    "operator_incident_report": ["annotations", "alarm_timeline"],
    "session_incidents": ["operator_incident_report", "recovery_report", "quality_timeline"],
    "resume_decision": ["resume_state", "session_incidents", "recovery_report", "session_integrity"],
    "event_log_index": ["command_journal", "alarm_timeline", "annotations", "recovery_report", "resume_decision"],
    "recovery_decision_timeline": ["recovery_report", "resume_decision"],
    "resume_attempts": ["resume_decision", "command_journal"],
    "resume_attempt_outcomes": ["resume_attempts", "resume_decision", "contract_consistency", "command_state_policy"],
    "command_state_policy": ["scan_plan"],
    "event_delivery_summary": ["event_log_index", "resume_attempt_outcomes", "contract_consistency"],
    "selected_execution_rationale": ["scan_plan"],
    "contract_consistency": ["scan_plan", "session_integrity", "diagnostics_pack", "resume_decision", "event_log_index"],
    "release_evidence_pack": ["contract_consistency", "session_integrity", "diagnostics_pack", "event_log_index", "recovery_decision_timeline", "session_report", "qa_pack"],
    "release_gate_decision": ["contract_consistency", "release_evidence_pack", "event_delivery_summary", "resume_attempt_outcomes", "selected_execution_rationale", "session_evidence_seal"],
    "control_plane_snapshot": ["summary_json", "release_gate_decision", "contract_consistency", "session_evidence_seal"],
    "control_authority_snapshot": ["summary_json", "scan_plan"],
    "bridge_observability_report": ["summary_json", "event_delivery_summary"],
    "artifact_registry_snapshot": ["scan_plan", "diagnostics_pack", "release_gate_decision"],
    "session_evidence_seal": ["control_plane_snapshot", "release_gate_decision", "artifact_registry_snapshot"],
}


def infer_dependencies(name: str) -> list[str]:
    """Return registry dependency names for a canonical artifact."""
    return list(_DEPENDENCY_MAP.get(name, []))
