from __future__ import annotations

from typing import Final


ARTIFACT_SCHEMA_HINTS: Final[dict[str, str]] = {
    "repo_truth_ledger": "session/repo_truth_ledger_v1.schema.json",
    "live_truth_ledger": "session/live_truth_ledger_v1.schema.json",
    "summary_json": "summary.schema.json",
    "session_report": "session_report.schema.json",
    "replay_index": "replay_index.schema.json",
    "quality_timeline": "quality_timeline.schema.json",
    "pressure_sensor_timeline": "pressure_sensor_timeline.schema.json",
    "ultrasound_frame_metrics": "ultrasound_frame_metrics.schema.json",
    "ultrasound_analysis": "ultrasound_analysis.schema.json",
    "pressure_analysis": "pressure_analysis.schema.json",
    "alarm_timeline": "alarm_event.schema.json",
    "qa_pack": "qa_pack.schema.json",
    "session_compare": "session_compare.schema.json",
    "session_trends": "session_trends.schema.json",
    "diagnostics_pack": "diagnostics_pack.schema.json",
    "device_readiness": "device_readiness.schema.json",
    "scan_plan": "runtime/scan_plan_v1.schema.json",
    "xmate_profile": "xmate_profile.schema.json",
    "patient_registration": "patient_registration.schema.json",
    "localization_readiness": "localization_readiness.schema.json",
    "calibration_bundle": "calibration_bundle.schema.json",
    "localization_freeze": "localization_freeze.schema.json",
    "manual_adjustment": "manual_adjustment.schema.json",
    "source_frame_set": "source_frame_set.schema.json",
    "registration_candidate": "registration_candidate.schema.json",
    "back_roi": "back_roi.schema.json",
    "midline_polyline": "midline_polyline.schema.json",
    "landmarks": "landmarks.schema.json",
    "body_surface": "body_surface.schema.json",
    "guidance_targets": "guidance_targets.schema.json",
    "localization_replay_index": "localization_replay_index.schema.json",
    "scan_protocol": "scan_protocol.schema.json",
    "frame_sync_index": "frame_sync_index.schema.json",
    "reconstruction_input_index": "reconstruction_input_index.schema.json",
    "training_bridge_model_ready_input_index": "training_bridge_model_ready_input_index.schema.json",
    "coronal_vpi": "coronal_vpi.schema.json",
    "bone_mask": "bone_mask.schema.json",
    "frame_anatomy_points": "frame_anatomy_points.schema.json",
    "lamina_candidates": "lamina_candidates.schema.json",
    "pose_series": "pose_series.schema.json",
    "reconstruction_evidence": "reconstruction_evidence.schema.json",
    "spine_curve": "spine_curve.schema.json",
    "prior_assisted_curve": "prior_assisted_curve.schema.json",
    "landmark_track": "landmark_track.schema.json",
    "reconstruction_summary": "reconstruction_summary.schema.json",
    "vpi_ranked_slices": "vpi_ranked_slices.schema.json",
    "vpi_bone_feature_mask": "bone_mask.schema.json",
    "vertebra_pairs": "vertebra_pairs.schema.json",
    "tilt_candidates": "tilt_candidates.schema.json",
    "cobb_measurement": "cobb_measurement.schema.json",
    "prior_assisted_cobb": "prior_assisted_cobb.schema.json",
    "uca_measurement": "uca_measurement.schema.json",
    "assessment_agreement": "assessment_agreement.schema.json",
    "assessment_summary": "assessment_summary.schema.json",
    "session_integrity": "artifact_registry.schema.json",
    "artifact_registry_snapshot": "artifact_registry.schema.json",
    "lineage": "session/lineage.schema.json",
    "resume_state": "session/resume_state.schema.json",
    "recovery_report": "session/recovery_report.schema.json",
    "operator_incident_report": "session/operator_incident_report.schema.json",
    "session_incidents": "session/session_incidents.schema.json",
    "resume_decision": "session/resume_decision.schema.json",
    "event_log_index": "session/event_log_index_v1.schema.json",
    "event_delivery_summary": "session/event_delivery_summary_v1.schema.json",
    "selected_execution_rationale": "session/selected_execution_rationale_v1.schema.json",
    "release_gate_decision": "runtime/release_gate_decision_v1.schema.json",
    "recovery_decision_timeline": "session/recovery_timeline_v1.schema.json",
    "resume_attempts": "session/resume_attempts_v1.schema.json",
    "resume_attempt_outcomes": "session/resume_attempt_outcomes_v1.schema.json",
    "contract_consistency": "session/contract_consistency_v1.schema.json",
    "release_evidence_pack": "session/release_evidence_pack_v1.schema.json",
    "command_state_policy": "runtime/command_state_policy_v1.schema.json",
    "command_policy_snapshot": "session/command_policy_snapshot_v1.schema.json",
    "contract_kernel_diff": "session/contract_kernel_diff_v1.schema.json",
    "session_evidence_seal": "session/session_evidence_seal_v1.schema.json",
    "postprocess_stage_manifest": "session/postprocess_stage_manifest_v1.schema.json",
    "session_intelligence_manifest": "session/session_intelligence_manifest_v1.schema.json",
}


def schema_for_artifact(name: str) -> str:
    """Return the schema hint registered for an artifact type."""
    return ARTIFACT_SCHEMA_HINTS.get(name, "")
