from enum import Enum


class CoreExecutionState(str, Enum):
    BOOT = "BOOT"
    DISCONNECTED = "DISCONNECTED"
    CONNECTED = "CONNECTED"
    POWERED = "POWERED"
    AUTO_READY = "AUTO_READY"
    SESSION_LOCKED = "SESSION_LOCKED"
    PATH_VALIDATED = "PATH_VALIDATED"
    APPROACHING = "APPROACHING"
    CONTACT_SEEKING = "CONTACT_SEEKING"
    CONTACT_STABLE = "CONTACT_STABLE"
    SCANNING = "SCANNING"
    PAUSED_HOLD = "PAUSED_HOLD"
    RECOVERY_RETRACT = "RECOVERY_RETRACT"
    SEGMENT_ABORTED = "SEGMENT_ABORTED"
    PLAN_ABORTED = "PLAN_ABORTED"
    RETREATING = "RETREATING"
    SCAN_COMPLETE = "SCAN_COMPLETE"
    FAULT = "FAULT"
    ESTOP = "ESTOP"


SystemState = CoreExecutionState
