function(robot_core_apply_sdk_policy target_name)
  if(ROBOT_CORE_PROFILE STREQUAL "prod" AND ROBOT_CORE_WITH_XCORE_SDK AND NOT VendoredRokaeSdk_FOUND)
    message(FATAL_ERROR "ROBOT_CORE_PROFILE=prod with ROBOT_CORE_WITH_XCORE_SDK=ON requires an explicit xCore SDK toolchain. Vendored fallback is disabled.")
  endif()
  if(ROBOT_CORE_PROFILE STREQUAL "prod" AND NOT ROBOT_CORE_WITH_XCORE_SDK AND NOT VendoredRokaeSdk_FOUND)
    message(STATUS "ROBOT_CORE_PROFILE=prod running in contract-only mode without a live xCore SDK toolchain")
  endif()
  if(VendoredRokaeSdk_FOUND)
    target_link_libraries(${target_name} PRIVATE Rokae::xCoreSDK)
    if(ROBOT_CORE_WITH_XMATE_MODEL AND TARGET Rokae::xMateModel)
      target_link_libraries(${target_name} PRIVATE Rokae::xMateModel)
    endif()
  endif()
endfunction()
